const DATA = [
    {
      "pdbOrd": 11,
      "pdbTitle": "Vessel Operated",
      "pdbDesc": "POMS keeps track of Vessel & Barge operations deploying Pilot & Tug.",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "vessel.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 43,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 107,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 374,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 1372
    },
    {
      "pdbOrd": 12,
      "pdbTitle": "Rake Handled",
      "pdbDesc": "POMS assists in managing Wagon operation, Rake formation and movement.",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "rake.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 101,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 245,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 1082,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 3076
    },
    {
      "pdbOrd": 13,
      "pdbTitle": "Vehicle Entered",
      "pdbDesc": "POMS manages 1200 Vehicles In-out, Loading-Unloading operation per day.",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "vehicle.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 12762,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 33415,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 91980,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 361624
    },
    {
      "pdbOrd": 14,
      "pdbTitle": "Bills Generated",
      "pdbDesc": "POMS generates 20 different types of Bills for Port Services. Implemented 4 Scale of Rate (SoR) and many Trade Circulars.",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "bills.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 8441,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 23065,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 60742,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 235038
    },
    {
      "pdbOrd": 22,
      "pdbTitle": "PDA accounts",
      "pdbDesc": "POMS manages Port Deposit Accounts of Stakeholder and share real-time transaction in website with Trust & Confidence.",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "pda.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 221,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 317,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 449,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 674
    },
    {
      "pdbOrd": 23,
      "pdbTitle": "Import Containers",
      "pdbDesc": "POMS manages Import Operation Cycle starting from Landing to Delivery including documentation & Customs-EDI.",
      "pdbUnit": "TEUs",
      "pdbAlign": "R",
      "pdbIcon": "import_cnt.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 9935,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 33048,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 85827,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 338541
    },
    {
      "pdbOrd": 24,
      "pdbTitle": "Export Containers",
      "pdbDesc": "POMS controls Export Operation Cycle starting from Export-Opening, Receiving to Shipment.",
      "pdbUnit": "TEUs",
      "pdbAlign": "R",
      "pdbIcon": "export_cnt.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 5230,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 31114,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 84587,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 331392
    },
    {
      "pdbOrd": 31,
      "pdbTitle": "Cargo Handled",
      "pdbDesc": "POMS captures Import-Export Cargo handling detail to generate  Invoices & Reports for Management.",
      "pdbUnit": "MT",
      "pdbAlign": "R",
      "pdbIcon": "cargo.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 86754,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 267865,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 767310,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 3208529
    },
    {
      "pdbOrd": 32,
      "pdbTitle": "Customs-EDI Message",
      "pdbDesc": "POMS processes 924 messages per day approximately on an average.",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "custom_edi.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 17463,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 41474,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 126444,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 451967
    },
    {
      "pdbOrd": 33,
      "pdbTitle": "IPA-PCS Message",
      "pdbDesc": "POMS exchanges 1265 messages per day approximately on an average.",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "ipa_pcs.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 24832,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 60116,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 171281,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 638348
    },
    {
      "pdbOrd": 34,
      "pdbTitle": "Internal Message",
      "pdbDesc": "POMS shares real-time business data to it's Business Partner (BKCT, Weighbridge & DLDS-LDB).",
      "pdbUnit": "",
      "pdbAlign": "N",
      "pdbIcon": "internal_msg.png",
      "pdbCmhTxt": "Aug, 2020",
      "pdbCmhQty": 82397,
      "pdbPmhTxt": "Aug, 2019",
      "pdbPmhQty": 558703,
      "pdbCfyTxt": "2020-21",
      "pdbCfyQty": 171281,
      "pdbPfyTxt": "2019-20",
      "pdbPfyQty": 1925541
    }
  ];

  export default DATA;